{"name": "TC1_001: Verify signup_with_invalid_data via UI", "status": "passed", "steps": [{"name": "Step 1: Signup to Contact List App with invalid Data", "status": "passed", "attachments": [{"name": "image", "source": "5e40d099-528b-429c-af98-76fef83fddeb-attachment.png", "type": "image/png"}], "start": 1736758257710, "stop": 1736758260532}, {"name": "Step 2: Verify Failed Signup", "status": "passed", "attachments": [{"name": "image", "source": "b2ad96ad-8520-494e-bed4-fbb70c4b73a8-attachment.png", "type": "image/png"}], "start": 1736758260532, "stop": 1736758261613}], "attachments": [{"name": "log", "source": "7e17a41a-30e8-417a-86e9-137986b3ca81-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user", "value": "{'firstName': 'Sandrix', 'lastName': 'Jimenix', 'email': 'Jimenix@example.com', 'password': '', 'result': 'User validation failed: password: Path `password` is required.'}"}], "start": 1736758257710, "stop": 1736758261613, "uuid": "3bda5685-d11c-4056-8d14-4eccd52f92aa", "historyId": "ffd225ca889fa8e7d0423308f52a5aaf", "testCaseId": "6509c706c67decc84e09c503a9c6463f", "fullName": "tests.ui.test_signup_via_ui.TestUserSignupFunctionality#test_signup_with_invalid_data_via_ui", "labels": [{"name": "parentSuite", "value": "Regression"}, {"name": "suite", "value": "User SignUp Functionality"}, {"name": "severity", "value": "normal"}, {"name": "subSuite", "value": "TC1_001: Verify signup_with_invalid_data via UI"}, {"name": "feature", "value": "User SignUp Functionality"}, {"name": "tag", "value": "tags('UI_SignUp_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "14480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_signup_via_ui"}]}