{"name": "TC4_004: Add Contact with invalid Data via API", "status": "passed", "steps": [{"name": "Step 1: Submit POST request with invalid data", "status": "passed", "start": 1737988706100, "stop": 1737988707203}, {"name": "Step 2: Verify failed  Add Contact", "status": "passed", "attachments": [{"name": "API Response", "source": "7b73b984-77bd-431f-972a-db77eee1602e-attachment.json", "type": "application/json"}], "start": 1737988707203, "stop": 1737988707207}], "attachments": [{"name": "log", "source": "9affc227-b623-4685-8d38-4554b63776a7-attachment.txt", "type": "text/plain"}], "start": 1737988706100, "stop": 1737988707207, "uuid": "bffbae24-1813-4587-94c7-d8b1263cfa88", "historyId": "e090cec3a16a1241e57392887e0922f4", "testCaseId": "e090cec3a16a1241e57392887e0922f4", "fullName": "tests.api.test_add_contact_via_api.TestAddContactFunctionality#test_verify_if_the_api_handles_invalid_contact_data", "labels": [{"name": "severity", "value": "normal"}, {"name": "suite", "value": "Contact Management Functionality"}, {"name": "feature", "value": "Contact Management Functionality"}, {"name": "parentSuite", "value": "Regression"}, {"name": "subSuite", "value": "TC4_004: Add Contact with invalid Data via API"}, {"name": "tag", "value": "tags('api_management_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "13628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_add_contact_via_api"}]}