{"name": "TC3_004: Log In with invalid credentials via API", "status": "passed", "steps": [{"name": "Step 1: Send POST request with invalid data ", "status": "passed", "steps": [{"name": "Step 2: Verify failed Login.", "status": "passed", "attachments": [{"name": "API Response", "source": "920f65d0-36c1-4596-aa3b-5b0800d38ac6-attachment.json", "type": "application/json"}], "start": 1737708111189, "stop": 1737708112214}], "start": 1737708111189, "stop": 1737708112214}], "attachments": [{"name": "log", "source": "d3009c22-75f7-4589-992c-b193bf033255-attachment.txt", "type": "text/plain"}], "start": 1737708111189, "stop": 1737708112215, "uuid": "614bce43-6554-4956-94b5-6b026754d49d", "historyId": "a2e24d3ae71a71bded3f9b0fe945fbb7", "testCaseId": "a2e24d3ae71a71bded3f9b0fe945fbb7", "fullName": "tests.api.test_login_via_api.TestUserLoginFunctionality#test_failed_login_via_api", "labels": [{"name": "subSuite", "value": "TC3_004: Log In with invalid credentials via API"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "User Login Functionality"}, {"name": "parentSuite", "value": "Regression"}, {"name": "suite", "value": "User Login Functionality"}, {"name": "tag", "value": "tags('api_login_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "3652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_login_via_api"}]}