{"name": "TC3_004: Log In with invalid credentials via API", "status": "passed", "steps": [{"name": "Step 1: Send POST request with invalid data ", "status": "passed", "steps": [{"name": "Step 2: Verify failed Login.", "status": "passed", "attachments": [{"name": "API Response", "source": "20ba0173-82f0-46ae-bec3-88e5a549e7a2-attachment.json", "type": "application/json"}], "start": 1737005057540, "stop": 1737005058618}], "start": 1737005057540, "stop": 1737005058618}], "attachments": [{"name": "logs", "source": "d64d5adb-65eb-4438-bda2-60a789b7f0df-attachment.txt", "type": "text/plain"}], "start": 1737005057540, "stop": 1737005058618, "uuid": "135d9007-a3b6-420f-8c2b-fc89732d9204", "historyId": "a2e24d3ae71a71bded3f9b0fe945fbb7", "testCaseId": "a2e24d3ae71a71bded3f9b0fe945fbb7", "fullName": "tests.api.test_login_via_api.TestUserLoginFunctionality#test_failed_login_via_api", "labels": [{"name": "feature", "value": "User Login Functionality"}, {"name": "parentSuite", "value": "Regression"}, {"name": "severity", "value": "normal"}, {"name": "subSuite", "value": "TC3_004: Log In with invalid credentials via API"}, {"name": "suite", "value": "User Login Functionality"}, {"name": "tag", "value": "tags('api_login_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "11780-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_login_via_api"}]}