{"name": "TC4_004: Add Contact with invalid Data via API", "status": "passed", "steps": [{"name": "Step 1: Submit POST request with invalid data", "status": "passed", "start": 1738075363198, "stop": 1738075364244}, {"name": "Step 2: Verify failed  Add Contact", "status": "passed", "attachments": [{"name": "API Response", "source": "4d32793a-9a85-473b-af31-271a5469f122-attachment.json", "type": "application/json"}], "start": 1738075364245, "stop": 1738075364248}], "attachments": [{"name": "log", "source": "ff19c1e6-76d6-47ca-a4a6-d2ff9f4ddc41-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "868b5685-c5d2-4bd9-bd5a-b6013d778c52-attachment.txt", "type": "text/plain"}], "start": 1738075363197, "stop": 1738075364248, "uuid": "014cf35f-e9e6-4bad-b7b0-42c8a0f5446c", "historyId": "e090cec3a16a1241e57392887e0922f4", "testCaseId": "e090cec3a16a1241e57392887e0922f4", "fullName": "tests.api.test_add_contact_via_api.TestAddContactFunctionality#test_verify_if_the_api_handles_invalid_contact_data", "labels": [{"name": "subSuite", "value": "TC4_004: Add Contact with invalid Data via API"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Contact Management Functionality"}, {"name": "parentSuite", "value": "Regression"}, {"name": "suite", "value": "Contact Management Functionality"}, {"name": "tag", "value": "tags('api_management_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "14260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_add_contact_via_api"}]}