{"name": "TC1_002: Signup_with_invalid_data via UI", "status": "passed", "steps": [{"name": "Step 1: Signup to Contact List App with invalid Data", "status": "passed", "attachments": [{"name": "image", "source": "371b56c8-348a-4f91-8ef0-8a965967e2fb-attachment.png", "type": "image/png"}], "start": 1736831080627, "stop": 1736831083145}, {"name": "Step 2: Verify Failed Signup", "status": "passed", "attachments": [{"name": "image", "source": "e28233e0-14ce-4f04-a35e-b90b1504071a-attachment.png", "type": "image/png"}], "start": 1736831083145, "stop": 1736831084222}], "attachments": [{"name": "log", "source": "a88863d1-c2d3-454d-bc84-dc626ef77fab-attachment.txt", "type": "text/plain"}], "start": 1736831080626, "stop": 1736831084222, "uuid": "109b8a22-ced0-4410-850a-e3e74f553eec", "historyId": "6509c706c67decc84e09c503a9c6463f", "testCaseId": "6509c706c67decc84e09c503a9c6463f", "fullName": "tests.ui.test_signup_via_ui.TestUserSignupFunctionality#test_signup_with_invalid_data_via_ui", "labels": [{"name": "severity", "value": "normal"}, {"name": "suite", "value": "User SignUp Functionality"}, {"name": "feature", "value": "User SignUp Functionality"}, {"name": "subSuite", "value": "TC1_002: Signup_with_invalid_data via UI"}, {"name": "parentSuite", "value": "Regression"}, {"name": "tag", "value": "tags('UI_SignUp_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "15096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_signup_via_ui"}]}