{"name": "TC4_004: Add Contact with invalid Data via API", "status": "passed", "steps": [{"name": "Step 1: Submit POST request with invalid data", "status": "passed", "start": 1737708095974, "stop": 1737708097015}, {"name": "Step 2: Verify failed  Add Contact", "status": "passed", "attachments": [{"name": "API Response", "source": "2d79d7c6-40b8-48f0-a17b-385bbacabeb3-attachment.json", "type": "application/json"}], "start": 1737708097015, "stop": 1737708097018}], "attachments": [{"name": "log", "source": "103ad3b2-9abf-4f96-b635-6d59389c0898-attachment.txt", "type": "text/plain"}], "start": 1737708095974, "stop": 1737708097019, "uuid": "01990d21-9199-49ff-9c25-a7163602590e", "historyId": "e090cec3a16a1241e57392887e0922f4", "testCaseId": "e090cec3a16a1241e57392887e0922f4", "fullName": "tests.api.test_add_contact_via_api.TestAddContactFunctionality#test_verify_if_the_api_handles_invalid_contact_data", "labels": [{"name": "feature", "value": "Contact Management Functionality"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "Regression"}, {"name": "suite", "value": "Contact Management Functionality"}, {"name": "subSuite", "value": "TC4_004: Add Contact with invalid Data via API"}, {"name": "tag", "value": "tags('api_management_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "3652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_add_contact_via_api"}]}