{"name": "TC3_004: Log In with invalid credentials via API", "status": "passed", "steps": [{"name": "Step 1: Send POST request with invalid data ", "status": "passed", "steps": [{"name": "Step 2: Verify failed Login.", "status": "passed", "attachments": [{"name": "API Response", "source": "4c90b6f0-1ef8-4927-a170-111d55859ed2-attachment.json", "type": "application/json"}], "start": 1738075393028, "stop": 1738075394192}], "start": 1738075393028, "stop": 1738075394192}], "attachments": [{"name": "log", "source": "6c0cf12f-e7ef-48f2-994a-e5aeff7c0b27-attachment.txt", "type": "text/plain"}], "start": 1738075393028, "stop": 1738075394192, "uuid": "4a107445-5b1f-45b2-a438-81999bc09cf0", "historyId": "a2e24d3ae71a71bded3f9b0fe945fbb7", "testCaseId": "a2e24d3ae71a71bded3f9b0fe945fbb7", "fullName": "tests.api.test_login_via_api.TestUserLoginFunctionality#test_failed_login_via_api", "labels": [{"name": "suite", "value": "User Login Functionality"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "User Login Functionality"}, {"name": "parentSuite", "value": "Regression"}, {"name": "subSuite", "value": "TC3_004: Log In with invalid credentials via API"}, {"name": "tag", "value": "tags('api_login_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "14260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_login_via_api"}]}