{"name": "TC4_004: Add Contact with invalid Data via API", "status": "passed", "steps": [{"name": "Step 1: Submit POST request with invalid data", "status": "passed", "start": 1738142551133, "stop": 1738142552131}, {"name": "Step 2: Verify failed  Add Contact", "status": "passed", "attachments": [{"name": "API Response", "source": "70f701e1-0fb4-4058-a7ec-89c6c3fdec75-attachment.json", "type": "application/json"}], "start": 1738142552131, "stop": 1738142552136}], "attachments": [{"name": "log", "source": "b5a67d2f-1459-4be6-b02b-6bb72cd55ede-attachment.txt", "type": "text/plain"}], "start": 1738142551133, "stop": 1738142552137, "uuid": "fc9f0ba7-4cd0-40bb-9ca2-03abd722f7e0", "historyId": "e090cec3a16a1241e57392887e0922f4", "testCaseId": "e090cec3a16a1241e57392887e0922f4", "fullName": "tests.api.test_add_contact_via_api.TestAddContactFunctionality#test_verify_if_the_api_handles_invalid_contact_data", "labels": [{"name": "feature", "value": "Contact Management Functionality"}, {"name": "suite", "value": "Contact Management Functionality"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "Regression"}, {"name": "subSuite", "value": "TC4_004: Add Contact with invalid Data via API"}, {"name": "tag", "value": "tags('api_management_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "18864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_add_contact_via_api"}]}